name: albadr tafsir-assadi update
run-name:  إضافة درس - شرح تفسير السعدي | الشيخ د. عبدالرزاق البدر

on:
  push:
    paths:
      - "mp3scraper/bin/Release/podcasts/شرح-تفسير-السعدي-(تيسير-الكريم-الرحمن-في-تفسير-كلام-المنان).xml"  # تشغيل فقط عند تعديل هذا الملف         
  workflow_dispatch:

permissions:
  contents: write
  
jobs:
  replace:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      # 1️⃣ سحب الشيفرة
      - name: Checkout repository
        uses: actions/checkout@v6
        with: 
          fetch-depth: 0   # احصل على التاريخ الكامل للسماح بالـ push
          persist-credentials: true
          token: ${{ secrets.R_token }}  

      # 2️⃣ تعريف مسار الملف (احرص على وضعه داخل علامات اقتباس)
      - name: Define file path
        id: vars
        run: |
          echo "FILE=mp3scraper/bin/Release/podcasts/شرح-تفسير-السعدي-(تيسير-الكريم-الرحمن-في-تفسير-كلام-المنان).xml" >> $GITHUB_OUTPUT

      # 3️⃣ البحث / الاستبدال باستخدام perl (regex مع وضع التعليقات)
      - name: Get new item
        id: get_item
        env:
          FILE: ${{ steps.vars.outputs.FILE }}
        run: |
          perl -0777 -pe '
            s{
              <\?xml\s+version="1\.0"\s+encoding="utf-8"\?>
              .*?
              </image>
              }{}gsx;  
            s{
             </channel>\s*</rss>\s*
              }{}gsx;  
          ' "$FILE" > item.txt
          
      - name: Checkout target repo
        uses: actions/checkout@v6
        with:
          repository: dev-fos/islampodcast   # استبدل بـ <المنظمة>/<المستودع>
          token: ${{ secrets.R_token }}   # لا تحتاج PAT
          path: target-repo
          fetch-depth: 0
          persist-credentials: true
          
      - name: Define target file path
        id: vars2
        run: |
          echo "FILE=target-repo/عبدالرزاق-البدر/التفسير-وعلوم-القرآن/شرح-تفسير-السعدي-(تيسير-الكريم-الرحمن-في-تفسير-كلام-المنان).xml" >> $GITHUB_OUTPUT

      - name: Read item file into output
        id: file_data
        run: |
          # قراءة محتوى الملف وتخزينه في متغير
          CONTENT=$(cat item.txt)
          # إرسال المحتوى إلى مخرجات GitHub Action
          echo "content<<EOF" >> $GITHUB_OUTPUT
          echo "$CONTENT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          
      - name: Update podcast in target repo
        env:
          FILE: ${{ steps.vars2.outputs.FILE }}
          LINES_FILE: ${{ steps.get_item.outputs.line }}
        run: |
          # قراءة محتوى LINES_FILE في متغيّر Bash
          INSERT=$(cat item.txt)
              perl -0777 -i -pe ' 
            s{
             </channel>\s*</rss>\s*
              }{
                ${{ steps.file_data.outputs.content }}
                </channel>
              </rss>
              }gsx;  
          ' "$FILE" 
            tail -n 100 "$FILE"
          
          
     # - name: Commit & push changes
     #   working-directory: target-repo
     #   run: |
     #     git config user.name  "github-actions[bot]"
     #     git config user.email "github-actions[bot]@users.noreply.github.com"
     #     git add mp3-url/al-badr-tafsir-assidi.html
     #     git commit -m "Update last_mp3.txt with new results" || echo "Nothing to commit"
     #     git push origin HEAD:main
