name: Run Windows Executable

on: [push]

jobs:
  run-exe:
    runs-on: windows-latest # Use a Windows runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 # Get your repository content

    - name: Run the executable
      run: .\mp3scraper\bin\Release\mp3scraper.exe  # Adjust path and arguments as needed
 
    - name: Upload generated file
      uses: actions/upload-artifact@v4
      with:
        name: my-generated-file
        path: /mp3scraper/bin/Release/podcasts/ # Replace with the actual path
        compression-level: 0
        if-no-files-found: ignore
