name: Run Windows Executable

on: [push]

jobs:
  run-exe:
    runs-on: windows-latest # Use a Windows runner
    outputs:
      output1: ${{ steps.run.outputs.artifact-id }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 # Get your repository content

    - name: Run the executable
      id : run
      run: .\mp3scraper\bin\Release\mp3scraper.exe  # Adjust path and arguments as needed
      
  upload:
    runs-on: windows-latest # Use a Windows runner
    needs: run-exe
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 # Get your repository content

    - name: Upload generated file      
      uses: actions/upload-artifact@v4
      with:
        name: ${{ needs.run-exe.outputs.output1 }}
        path: .\mp3scraper\bin\Release\podcasts\ # Replace with the actual path
        compression-level: 9
        if-no-files-found: ignore
