name: Run Windows Executable

on:
  push:
    paths:
      - mp3scraper/bin/Release/mp3scraper.exe.config   # تشغيل فقط عند تعديل هذا الملف         
      - al-badr/تفسير-السعدي/mp3scraper.exe.config
  workflow_dispatch:

permissions:
  contents: write   

jobs:
  run-exe:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          persist-credentials: true
          fetch-depth: 0
          token: ${{ secrets.R_token }}

      - name: Determine which trigger fired
        id: which
        shell: bash
        run: |
          # احصل على القائمة الكاملة للملفات التي تغيرت
          MODIFIED=$(jq -r '.head_commit.modified[]' "$GITHUB_EVENT_PATH")
          
          # تحقق من وجود كل مسار
          if echo "$MODIFIED" | grep -q '^mp3scraper/bin/Release/mp3scraper.exe.config$'; then
            echo "trigger=Release" >> "$GITHUB_OUTPUT"
          elif echo "$MODIFIED" | grep -q '^al-badr/تفسير-السعدي/mp3scraper.exe.config$'; then
            echo "trigger=al-badr" >> "$GITHUB_OUTPUT"
          else
            echo "trigger=none" >> "$GITHUB_OUTPUT"
          fi
          
      - name: Run the executable
        run: |
          if [[ "${{ steps.which.outputs.trigger }}" == "Release" ]]; then
            .\mp3scraper\bin\Release\mp3scraper.exe
            # ضع أمر exe_config هنا
          elif [[ "${{ steps.which.outputs.trigger }}" == "al-badr" ]]; then
            .\al-badr/تفسير-السعدي/mp3scraper.exe.config
            # ضع أمر src_changes هنا
          fi


      - name: Upload generated file
        uses: actions/upload-artifact@v7
        with:
          name: ${{ github.run_id }}
          path: .\mp3scraper\bin\Release\podcasts\
       #   archive: false
          compression-level: 9
          if-no-files-found: ignore

      # 4️⃣ إضافة الملف المُولَّد إلى المستودع نفسه
      - name: Commit generated files back to repo
        shell: bash
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add mp3scraper/bin/Release/podcasts/
          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          git commit -m "Add generated podcasts (auto‑generated by workflow)"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.R_token }}
