name: Run Windows Executable

on:
  push:
    paths:
      - mp3scraper/bin/Release/mp3scraper.exe.config   # تشغيل فقط عند تعديل هذا الملف         
      - al-badr/تفسير-السعدي/mp3scraper.exe.config
  workflow_dispatch:

permissions:
  contents: write   

jobs:
  run-exe:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          persist-credentials: true
          fetch-depth: 0
          token: ${{ secrets.R_token }}

      - name: Determine which trigger fired
        id: which
        run: |
          $event = Get-Content $env:GITHUB_EVENT_PATH -Raw | ConvertFrom-Json
      
          # الحصول على المصفوفة إذا وجدت
          $modified = $null
          if ($event.head_commit -and $event.head_commit.modified) {
            $modified = $event.head_commit.modified
          }
      
          if (-not $modified) {
            "trigger=none" >> $env:GITHUB_OUTPUT
            exit 0
          }
      
          $text = $modified -join "`n"
      
          if ($text -match '^mp3scraper/bin/Release/mp3scraper\.exe\.config$') {
            "trigger=Release" >> $env:GITHUB_OUTPUT
          }
          elseif ($text -match '^al-badr/تفسير-السعدي/mp3scraper\.exe\.config$') {
            "trigger=al-badr" >> $env:GITHUB_OUTPUT
          }
          else {
            "trigger=none" >> $env:GITHUB_OUTPUT
          }
          echo "تم اختيار trigger = ${{ steps.which.outputs.trigger }}"

         
      
      - name: Run appropriate exe
        if: steps.which.outputs.trigger != 'none'   # (اختياري)
        run: |
          $trigger = "${{ steps.which.outputs.trigger }}"
      
          if ($trigger -eq 'Release') {
              & ".\mp3scraper\bin\Release\mp3scraper.exe"
              # ضع أمر exe_config هنا إذا لزم
          }
          elseif ($trigger -eq 'al-badr') {
              & ".\al-badr\تفسير-السعدي\mp3scraper.exe"
              # ضع أمر src_changes هنا إذا لزم
          }



      - name: Upload generated file
        uses: actions/upload-artifact@v7
        with:
          name: ${{ github.run_id }}
          path: .\mp3scraper\bin\Release\podcasts\
       #   archive: false
          compression-level: 9
          if-no-files-found: ignore

      # 4️⃣ إضافة الملف المُولَّد إلى المستودع نفسه
      - name: Commit generated files back to repo
        shell: bash
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add mp3scraper/bin/Release/podcasts/
          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          git commit -m "Add generated podcasts (auto‑generated by workflow)"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.R_token }}
